# Pwn

bfbo:
    build: ./pwn/100-bfbo/src
    ports:
        - 10001:10001
    security_opt:
        - seccomp:unconfined

bfpl:
    build: ./pwn/200-bfpl/src
    ports:
        - 10002:10002
    security_opt:
        - seccomp:unconfined

# Web

tmi:
    build: ./web/100-tmi/src
    ports:
        - 5000:5000

buynow:
    build: ./web/200-buynow/src
    ports:
        - 5001:5001
